create extension if not exists pgcrypto;
create extension if not exists citext;

create table if not exists technicians (
  id uuid primary key default gen_random_uuid(),
  code citext not null unique,
  name text not null default '',
  role text not null default 'tech' check (role in ('tech', 'admin')),
  zone text,
  active boolean not null default true,
  avatar_url text,
  last_login timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists technician_credentials (
  technician_id uuid primary key references technicians(id) on delete cascade,
  pin_hash text,
  legacy_pin text,
  updated_at timestamptz not null default now(),
  check (pin_hash is not null or legacy_pin is not null)
);

create table if not exists sessions (
  id uuid primary key default gen_random_uuid(),
  technician_id uuid not null references technicians(id) on delete cascade,
  token_hash char(64) not null unique,
  ip_address inet,
  user_agent text,
  created_at timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  expires_at timestamptz not null
);

create table if not exists sites (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  type text not null default 'mobile',
  lat double precision,
  lng double precision,
  address text,
  code_anfr text,
  code_nidt text,
  technologies text[] not null default '{}',
  operator text,
  owner text,
  access_info text,
  access_key text,
  access_lat double precision,
  access_lng double precision,
  anfr_support_id bigint,
  poi_category text,
  needs_4x4 boolean not null default false,
  needs_binome boolean not null default false,
  needs_terrasse boolean not null default false,
  has_wc boolean not null default false,
  has_abloy boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists notes (
  id uuid primary key default gen_random_uuid(),
  site_id uuid not null references sites(id) on delete cascade,
  content text not null,
  technician_code citext not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists photos (
  id uuid primary key default gen_random_uuid(),
  site_id uuid not null references sites(id) on delete cascade,
  url text not null,
  filename text,
  technician_code citext not null,
  created_at timestamptz not null default now()
);

create table if not exists activity_log (
  id uuid primary key default gen_random_uuid(),
  site_id uuid references sites(id) on delete cascade,
  technician_code citext not null,
  action text not null,
  details text,
  created_at timestamptz not null default now()
);

create table if not exists visits (
  id uuid primary key default gen_random_uuid(),
  site_id uuid references sites(id) on delete cascade,
  technician_code citext not null,
  visited_at timestamptz not null default now()
);

create table if not exists login_logs (
  id uuid primary key default gen_random_uuid(),
  technician_code citext not null,
  success boolean not null,
  created_at timestamptz not null default now()
);

create table if not exists ratings (
  id uuid primary key default gen_random_uuid(),
  site_id uuid not null references sites(id) on delete cascade,
  technician_code citext not null,
  score smallint not null check (score between 1 and 5),
  created_at timestamptz not null default now(),
  unique (site_id, technician_code)
);

create table if not exists anfr_data (
  id bigint primary key,
  support_id bigint,
  station_anfr text,
  operateur text,
  lat double precision,
  lng double precision,
  adresse text,
  code_postal text,
  commune text,
  departement text,
  hauteur_support double precision,
  antenne_id bigint,
  azimut double precision,
  hauteur_antenne double precision,
  systeme text,
  generation text,
  frequence text,
  imported_at timestamptz not null default now()
);

create table if not exists directory (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  phone text,
  email text,
  notes text,
  color text,
  author_code citext,
  author_name text,
  created_at timestamptz not null default now()
);

create table if not exists notebooks (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  icon text,
  color text,
  position integer not null default 0,
  author_code citext,
  author_name text,
  note_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists note_sections (
  id bigint generated by default as identity primary key,
  notebook_id bigint not null references notebooks(id) on delete cascade,
  name text not null,
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists notes_content (
  id bigint generated by default as identity primary key,
  notebook_id bigint not null references notebooks(id) on delete cascade,
  section_id bigint references note_sections(id) on delete set null,
  title text not null,
  content text not null,
  lat double precision,
  lng double precision,
  votes integer not null default 0,
  author_code citext,
  author_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists note_comments (
  id bigint generated by default as identity primary key,
  note_id bigint not null references notes_content(id) on delete cascade,
  content text not null,
  author_code citext,
  author_name text,
  created_at timestamptz not null default now()
);

create table if not exists announcements (
  id uuid primary key default gen_random_uuid(),
  message text not null,
  author_code citext,
  author_name text,
  created_at timestamptz not null default now(),
  expires_at timestamptz
);

create table if not exists trash (
  id bigint generated by default as identity primary key,
  item_type text not null,
  original_id text,
  item_data jsonb not null,
  label text not null,
  deleted_by_code citext,
  deleted_by_name text,
  deleted_at timestamptz not null default now()
);

create table if not exists game_sessions (
  id bigint generated by default as identity primary key,
  code text not null,
  host_code citext not null,
  status text not null default 'waiting',
  with_bots boolean not null default false,
  weapons boolean not null default false,
  created_at timestamptz not null default now(),
  ended_at timestamptz
);

create table if not exists game_players (
  id bigint generated by default as identity primary key,
  session_id bigint not null references game_sessions(id) on delete cascade,
  player_code citext not null,
  name text not null,
  color text,
  x double precision not null default 0,
  y double precision not null default 0,
  mass integer not null default 10,
  alive boolean not null default true,
  last_seen timestamptz not null default now(),
  unique (session_id, player_code)
);

create table if not exists td_sessions (
  id bigint generated by default as identity primary key,
  code text not null,
  host_code citext not null,
  status text not null default 'waiting',
  wave integer not null default 0,
  lives integer not null default 100,
  gold integer not null default 350,
  created_at timestamptz not null default now()
);

create table if not exists td_players (
  id bigint generated by default as identity primary key,
  session_id bigint not null references td_sessions(id) on delete cascade,
  player_code citext not null,
  name text not null,
  created_at timestamptz not null default now(),
  unique (session_id, player_code)
);

create table if not exists bacteria_sessions (
  id bigint generated by default as identity primary key,
  code text not null,
  host_code citext not null,
  host_name text,
  guest_code citext,
  guest_name text,
  status text not null default 'waiting',
  board text not null,
  turn integer not null default 1,
  move_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists upload_records (
  id uuid primary key default gen_random_uuid(),
  file_name text not null unique,
  site_id uuid references sites(id) on delete cascade,
  uploader_code citext not null,
  original_name text,
  mime_type text not null,
  size_bytes bigint not null,
  created_at timestamptz not null default now()
);

create table if not exists fuel_brands (
  station_id bigint primary key,
  brand text not null,
  updated_at timestamptz not null default now()
);

create index if not exists sessions_token_hash_idx on sessions(token_hash);
create index if not exists sessions_expires_at_idx on sessions(expires_at);
create index if not exists sites_name_idx on sites(name);
create index if not exists sites_type_idx on sites(type);
create index if not exists notes_site_created_idx on notes(site_id, created_at);
create index if not exists photos_site_created_idx on photos(site_id, created_at);
create index if not exists activity_site_created_idx on activity_log(site_id, created_at);
create index if not exists visits_technician_date_idx on visits(technician_code, visited_at);
create index if not exists anfr_support_idx on anfr_data(support_id);
create index if not exists anfr_position_idx on anfr_data(lat, lng);
create index if not exists game_sessions_code_status_idx on game_sessions(code, status);
create index if not exists td_sessions_code_status_idx on td_sessions(code, status);
create index if not exists bacteria_sessions_code_status_idx on bacteria_sessions(code, status);

create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists sites_set_updated_at on sites;
create trigger sites_set_updated_at before update on sites
for each row execute function set_updated_at();

drop trigger if exists notes_set_updated_at on notes;
create trigger notes_set_updated_at before update on notes
for each row execute function set_updated_at();

drop trigger if exists notes_content_set_updated_at on notes_content;
create trigger notes_content_set_updated_at before update on notes_content
for each row execute function set_updated_at();

create or replace function refresh_notebook_note_count()
returns trigger language plpgsql as $$
begin
  update notebooks
     set note_count = (select count(*) from notes_content where notebook_id = coalesce(new.notebook_id, old.notebook_id))
   where id = coalesce(new.notebook_id, old.notebook_id);
  return null;
end;
$$;

drop trigger if exists notes_content_refresh_count on notes_content;
create trigger notes_content_refresh_count
after insert or delete or update of notebook_id on notes_content
for each row execute function refresh_notebook_note_count();
